INSERT INTO `posts` (`id`, `user_id`, `category_id`, `slug`, `title`, `excerpt`, `body`, `created_at`, `updated_at`, `published_at`) VALUES
(1, 2, 1, 'my-first-post', 'My <strong>First</strong> Post', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '2023-01-25 15:06:48', '2023-01-25 15:41:43', NULL),
(2, 2, 1, 'my-second-post', 'Eloquent is Amazing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '2023-01-25 15:34:48', '2023-01-25 15:39:40', NULL),
(3, 5, 3, 'my-third-post', 'My Third Post', 'This is an excerpt', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', '2023-01-25 16:16:13', '2023-01-25 16:17:23', NULL),
(4, 5, 1, 'my-family-post', 'My Family Post', 'Excerpt for my post', 'Lorem ipsum dolor sit amet', '2023-01-26 10:44:06', '2023-01-26 10:44:06', NULL),
(5, 9, 2, 'my-work-post', 'My Work Post', 'Excerpt for my post', 'Lorem ipsum dolor sit amet', '2023-01-26 10:47:08', '2023-01-26 10:47:08', NULL),
(6, 11, 1, 'my-hobby-post', 'My Hobby Post', 'Excerpt for my post', 'Lorem ipsum dolor sit amet', '2023-01-26 10:48:02', '2023-01-26 10:48:02', NULL);
COMMIT;

